[[redirects]]
  from = "https://docs-mbktechstudio.netlify.app/*"
  to = "https://docs.mbktechstudio.com/:splat"
  status = 301
  force = true 

# Redirect /docs/SMP to /SMP
[[redirects]]
  from = "/docs/SMP/*"
  to = "/SMP/:splat"
  status = 301
 

#[[redirects]]
#  from = "https://docs-mbktechstudio.netlify.app/*"
#  to = "https://project.mbktechstudio.com/:splat"
#  status = 301
#  force = true

#[[redirects]]
#  from = "https://docs.mbktechstudio.com/*"
#  to = "https://project.mbktechstudio.com/:splat"
#  status = 301
#  force = true

