#[[redirects]]
#  from = "https://docs-mbktechstudio.netlify.app/*"
#  to = "https://project.mbktechstudio.com/:splat"
#  status = 301
#  force = true

#[[redirects]]
#  from = "https://docs.mbktechstudio.com/*"
#  to = "https://project.mbktechstudio.com/:splat"
#  status = 301
#  force = true

# Redirect root path (/) to project.mbktechstudio.com
[[redirects]]
  from = "https://docs-mbktechstudio.netlify.app/"
  to = "https://project.mbktechstudio.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.mbktechstudio.com/"
  to = "https://project.mbktechstudio.com/"
  status = 301
  force = true

# Redirect all subpaths to docs.mbktechstudio.com
[[redirects]]
  from = "https://docs-mbktechstudio.netlify.app/*"
  to = "https://docs.mbktechstudio.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.mbktechstudio.com/*"
  to = "https://docs.mbktechstudio.com/:splat"
  status = 301
  force = true
